///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DemoApplication
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the DemoApplicationRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("583dca41-cd2d-4060-8236-2b296d0e0f8f")]
    public partial class DemoApplicationRepository : RepoGenBaseFolder
    {
        static DemoApplicationRepository instance = new DemoApplicationRepository();
        DemoApplicationRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the DemoApplicationRepository element repository.
        /// </summary>
        [RepositoryFolder("583dca41-cd2d-4060-8236-2b296d0e0f8f")]
        public static DemoApplicationRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public DemoApplicationRepository() 
            : base("DemoApplicationRepository", "/", null, 0, false, "583dca41-cd2d-4060-8236-2b296d0e0f8f", ".\\RepositoryImages\\DemoApplicationRepository583dca41.rximgres")
        {
            _applicationundertest = new DemoApplicationRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("583dca41-cd2d-4060-8236-2b296d0e0f8f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("b99cbec9-fb64-4efc-bef5-e7bae7f8a37e")]
        public virtual DemoApplicationRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class DemoApplicationRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("b99cbec9-fb64-4efc-bef5-e7bae7f8a37e")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            DemoApplicationRepositoryFolders.RxTabIntroductionFolder _rxtabintroduction;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/form[@processname='RxDemoApp']", parentFolder, 30000, null, true, "b99cbec9-fb64-4efc-bef5-e7bae7f8a37e", "")
            {
                _rxtabintroduction = new DemoApplicationRepositoryFolders.RxTabIntroductionFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b99cbec9-fb64-4efc-bef5-e7bae7f8a37e")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b99cbec9-fb64-4efc-bef5-e7bae7f8a37e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The RxTabIntroduction folder.
            /// </summary>
            [RepositoryFolder("d97ebd21-522f-4654-a064-be1d5389df22")]
            public virtual DemoApplicationRepositoryFolders.RxTabIntroductionFolder RxTabIntroduction
            {
                get { return _rxtabintroduction; }
            }
        }

        /// <summary>
        /// The RxTabIntroductionFolder folder.
        /// </summary>
        [RepositoryFolder("d97ebd21-522f-4654-a064-be1d5389df22")]
        public partial class RxTabIntroductionFolder : RepoGenBaseFolder
        {
            RepoItemInfo _btnsubmitusernameInfo;
            RepoItemInfo _rxlinkbtnresetInfo;
            RepoItemInfo _txtusernameInfo;

            /// <summary>
            /// Creates a new RxTabIntroduction  folder.
            /// </summary>
            public RxTabIntroductionFolder(RepoGenBaseFolder parentFolder) :
                    base("RxTabIntroduction", "?/?/tabpage[@controlname='RxTabIntroduction']", parentFolder, 30000, null, false, "d97ebd21-522f-4654-a064-be1d5389df22", "")
            {
                _btnsubmitusernameInfo = new RepoItemInfo(this, "BtnSubmitUserName", "button[@controlname='btnSubmitUserName']", 30000, null, "6613a9cc-8e8e-4193-be93-03ccfc149d7f");
                _rxlinkbtnresetInfo = new RepoItemInfo(this, "RxLinkBtnReset", "link[@controlname='RxLinkBtnReset']", 30000, null, "4a421857-fe5d-43ba-a0e9-fab6ec159711");
                _txtusernameInfo = new RepoItemInfo(this, "TxtUserName", "text[@controlname='txtUserName']", 30000, null, "76f5af5d-a60b-4022-9168-813867953fc6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d97ebd21-522f-4654-a064-be1d5389df22")]
            public virtual Ranorex.TabPage Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d97ebd21-522f-4654-a064-be1d5389df22")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item.
            /// </summary>
            [RepositoryItem("6613a9cc-8e8e-4193-be93-03ccfc149d7f")]
            public virtual Ranorex.Button BtnSubmitUserName
            {
                get
                {
                    return _btnsubmitusernameInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtnSubmitUserName item info.
            /// </summary>
            [RepositoryItemInfo("6613a9cc-8e8e-4193-be93-03ccfc149d7f")]
            public virtual RepoItemInfo BtnSubmitUserNameInfo
            {
                get
                {
                    return _btnsubmitusernameInfo;
                }
            }

            /// <summary>
            /// The RxLinkBtnReset item.
            /// </summary>
            [RepositoryItem("4a421857-fe5d-43ba-a0e9-fab6ec159711")]
            public virtual Ranorex.Link RxLinkBtnReset
            {
                get
                {
                    return _rxlinkbtnresetInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The RxLinkBtnReset item info.
            /// </summary>
            [RepositoryItemInfo("4a421857-fe5d-43ba-a0e9-fab6ec159711")]
            public virtual RepoItemInfo RxLinkBtnResetInfo
            {
                get
                {
                    return _rxlinkbtnresetInfo;
                }
            }

            /// <summary>
            /// The TxtUserName item.
            /// </summary>
            [RepositoryItem("76f5af5d-a60b-4022-9168-813867953fc6")]
            public virtual Ranorex.Text TxtUserName
            {
                get
                {
                    return _txtusernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TxtUserName item info.
            /// </summary>
            [RepositoryItemInfo("76f5af5d-a60b-4022-9168-813867953fc6")]
            public virtual RepoItemInfo TxtUserNameInfo
            {
                get
                {
                    return _txtusernameInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}