///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace DemoApplication
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("9bfecf66-2d4d-40d8-ba5c-645d3cb0071b", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the DemoApplicationRepository repository.
        /// </summary>
        public static DemoApplicationRepository repo = DemoApplicationRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabIntroduction.TxtUserName' at 45;16.", repo.ApplicationUnderTest.RxTabIntroduction.TxtUserNameInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.RxTabIntroduction.TxtUserName.Click("45;16");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'piotr' with focus on 'ApplicationUnderTest.RxTabIntroduction.TxtUserName'.", repo.ApplicationUnderTest.RxTabIntroduction.TxtUserNameInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.RxTabIntroduction.TxtUserName.PressKeys("piotr");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabIntroduction.BtnSubmitUserName' at 52;21.", repo.ApplicationUnderTest.RxTabIntroduction.BtnSubmitUserNameInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.RxTabIntroduction.BtnSubmitUserName.Click("52;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='piotr') on item 'ApplicationUnderTest.RxTabIntroduction.TxtUserName'.", repo.ApplicationUnderTest.RxTabIntroduction.TxtUserNameInfo, new RecordItemIndex(3));
            Validate.AttributeEqual(repo.ApplicationUnderTest.RxTabIntroduction.TxtUserNameInfo, "Text", "piotr");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.RxTabIntroduction.RxLinkBtnReset' at 20;5.", repo.ApplicationUnderTest.RxTabIntroduction.RxLinkBtnResetInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.RxTabIntroduction.RxLinkBtnReset.Click("20;5");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
